import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../../style/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
const montserrat = Montserrat({ subsets: ["latin"], weight: "600" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={montserrat.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
